// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DebugImagePathConstruction(arg1:string):Promise<string>;

export function DelSessionBookMask(arg1:string):Promise<string>;

export function ExportPathIsCanWrite():Promise<boolean>;

export function ExportWeChatAllData(arg1:boolean,arg2:string):Promise<void>;

export function ExportWeChatDataByUserName(arg1:string,arg2:string):Promise<string>;

export function ExportWeChatDataWithIncrementalBackup(arg1:boolean,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function GetAppIsFirstStart():Promise<boolean>;

export function GetAppIsShareData():Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetExportPathStat():Promise<string>;

export function GetIncrementalBackupConfig():Promise<string>;

export function GetNewMessageExportConfig():Promise<string>;

export function GetSessionBookMaskList(arg1:string):Promise<string>;

export function GetSessionLastTime(arg1:string):Promise<string>;

export function GetWeChatAllInfo():Promise<string>;

export function GetWeChatRoomUserList(arg1:string):Promise<string>;

export function GetWeChatUserList():Promise<string>;

export function GetWechatContactList(arg1:number,arg2:number):Promise<string>;

export function GetWechatLocalAccountInfo():Promise<string>;

export function GetWechatMessageDate(arg1:string):Promise<string>;

export function GetWechatMessageListByKeyWord(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GetWechatMessageListByTime(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function GetWechatMessageListByType(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<string>;

export function GetWechatSessionList(arg1:number,arg2:number):Promise<string>;

export function OepnLogFileExplorer():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenExportPath():Promise<void>;

export function OpenFileOrExplorer(arg1:string,arg2:boolean):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SelectedDirDialog(arg1:string):Promise<string>;

export function SetIncrementalBackupConfig(arg1:main.IncrementalBackupConfig):Promise<boolean>;

export function SetNewMessageExportConfig(arg1:main.NewMessageExportConfig):Promise<boolean>;

export function SetSessionBookMask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetSessionLastTime(arg1:string,arg2:number,arg3:string):Promise<string>;

export function TestActualImageMessage(arg1:string):Promise<string>;

export function TestActualImagePathDebug(arg1:string):Promise<string>;

export function TestAutoUpdateTime():Promise<string>;

export function TestFileStorageNewDataBackup(arg1:string):Promise<string>;

export function TestImagePathFix(arg1:string):Promise<string>;

export function TestMediaFileBackup(arg1:string):Promise<string>;

export function TestMsgAttachImagePath(arg1:string):Promise<string>;

export function TestNewMessageExport(arg1:string):Promise<string>;

export function WeChatInit():Promise<void>;

export function WechatSwitchAccount(arg1:string):Promise<boolean>;
