// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugImagePathConstruction(arg1) {
  return window['go']['main']['App']['DebugImagePathConstruction'](arg1);
}

export function DelSessionBookMask(arg1) {
  return window['go']['main']['App']['DelSessionBookMask'](arg1);
}

export function ExportPathIsCanWrite() {
  return window['go']['main']['App']['ExportPathIsCanWrite']();
}

export function ExportWeChatAllData(arg1, arg2) {
  return window['go']['main']['App']['ExportWeChatAllData'](arg1, arg2);
}

export function ExportWeChatDataByUserName(arg1, arg2) {
  return window['go']['main']['App']['ExportWeChatDataByUserName'](arg1, arg2);
}

export function ExportWeChatDataWithIncrementalBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportWeChatDataWithIncrementalBackup'](arg1, arg2, arg3, arg4);
}

export function GetAppIsFirstStart() {
  return window['go']['main']['App']['GetAppIsFirstStart']();
}

export function GetAppIsShareData() {
  return window['go']['main']['App']['GetAppIsShareData']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetExportPathStat() {
  return window['go']['main']['App']['GetExportPathStat']();
}

export function GetIncrementalBackupConfig() {
  return window['go']['main']['App']['GetIncrementalBackupConfig']();
}

export function GetNewMessageExportConfig() {
  return window['go']['main']['App']['GetNewMessageExportConfig']();
}

export function GetSessionBookMaskList(arg1) {
  return window['go']['main']['App']['GetSessionBookMaskList'](arg1);
}

export function GetSessionLastTime(arg1) {
  return window['go']['main']['App']['GetSessionLastTime'](arg1);
}

export function GetWeChatAllInfo() {
  return window['go']['main']['App']['GetWeChatAllInfo']();
}

export function GetWeChatRoomUserList(arg1) {
  return window['go']['main']['App']['GetWeChatRoomUserList'](arg1);
}

export function GetWeChatUserList() {
  return window['go']['main']['App']['GetWeChatUserList']();
}

export function GetWechatContactList(arg1, arg2) {
  return window['go']['main']['App']['GetWechatContactList'](arg1, arg2);
}

export function GetWechatLocalAccountInfo() {
  return window['go']['main']['App']['GetWechatLocalAccountInfo']();
}

export function GetWechatMessageDate(arg1) {
  return window['go']['main']['App']['GetWechatMessageDate'](arg1);
}

export function GetWechatMessageListByKeyWord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetWechatMessageListByKeyWord'](arg1, arg2, arg3, arg4, arg5);
}

export function GetWechatMessageListByTime(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetWechatMessageListByTime'](arg1, arg2, arg3, arg4);
}

export function GetWechatMessageListByType(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetWechatMessageListByType'](arg1, arg2, arg3, arg4, arg5);
}

export function GetWechatSessionList(arg1, arg2) {
  return window['go']['main']['App']['GetWechatSessionList'](arg1, arg2);
}

export function OepnLogFileExplorer() {
  return window['go']['main']['App']['OepnLogFileExplorer']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenExportPath() {
  return window['go']['main']['App']['OpenExportPath']();
}

export function OpenFileOrExplorer(arg1, arg2) {
  return window['go']['main']['App']['OpenFileOrExplorer'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SelectedDirDialog(arg1) {
  return window['go']['main']['App']['SelectedDirDialog'](arg1);
}

export function SetIncrementalBackupConfig(arg1) {
  return window['go']['main']['App']['SetIncrementalBackupConfig'](arg1);
}

export function SetNewMessageExportConfig(arg1) {
  return window['go']['main']['App']['SetNewMessageExportConfig'](arg1);
}

export function SetSessionBookMask(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionBookMask'](arg1, arg2, arg3);
}

export function SetSessionLastTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionLastTime'](arg1, arg2, arg3);
}

export function TestActualImageMessage(arg1) {
  return window['go']['main']['App']['TestActualImageMessage'](arg1);
}

export function TestActualImagePathDebug(arg1) {
  return window['go']['main']['App']['TestActualImagePathDebug'](arg1);
}

export function TestFileStorageNewDataBackup(arg1) {
  return window['go']['main']['App']['TestFileStorageNewDataBackup'](arg1);
}

export function TestImagePathFix(arg1) {
  return window['go']['main']['App']['TestImagePathFix'](arg1);
}

export function TestMediaFileBackup(arg1) {
  return window['go']['main']['App']['TestMediaFileBackup'](arg1);
}

export function TestMsgAttachImagePath(arg1) {
  return window['go']['main']['App']['TestMsgAttachImagePath'](arg1);
}

export function TestNewMessageExport(arg1) {
  return window['go']['main']['App']['TestNewMessageExport'](arg1);
}

export function WeChatInit() {
  return window['go']['main']['App']['WeChatInit']();
}

export function WechatSwitchAccount(arg1) {
  return window['go']['main']['App']['WechatSwitchAccount'](arg1);
}
